// Contract addresses by chain ID
// This file is automatically generated from deployment artifacts
export const MiningChallengeAddresses: Record<string, { address?: `0x${string}`; chainId?: number; chainName?: string }> = {
  "31337": {
    "chainId": 31337,
    "chainName": "Hardhat Local"
  },
  "11155111": {
    "address": "0xe62177c707dE60D817814C6981eb67D0C042AC2e",
    "chainId": 11155111,
    "chainName": "Sepolia"
  }
};
